# Stage 1: Build React app
FROM node:20-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm cache clean --force && npm install --legacy-peer-deps
COPY . .

# Use ARG to accept the backend URL during build and then set it as an ENV var
ARG REACT_APP_BACKEND_API_URL_ARG
ENV REACT_APP_BACKEND_API_URL=$REACT_APP_BACKEND_API_URL_ARG

RUN npm run build # This will now use the ENV var for the build

# Stage 2: Serve React app with Nginx
FROM nginx:stable-alpine as production-stage

# Copy the custom Nginx configuration
COPY default.conf /etc/nginx/conf.d/default.conf

# This is the critical line: Copy the *contents* of the 'build' folder
# from the build-stage to Nginx's serving directory.
COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]